### ISSUE TITLE
Commercial version

### ISSUE THREAD

**Issue by ref-dat** [karthik947/BinanceTriangularArbitrage_v2#5]
Hi bro, how are you?

I've contacted you via your Email according to make this scanning code as a bot that takes actions and get those profits,

We can have a deal about it if you interested,

This is my Email:
a.himite@gmail.com

Best Regards,

**Comment by PlinMartinez** [comment]
Hello,

 

The code it´s free

 

It Works but don´t give profits by latency and other buyers

 

So i´m working with new bots and no more with this one 

Sorry

 

 

 

Best Regards & Saludos,

Manuel Paz

 

De: ref-dat <notifications@github.com> 
Enviado el: martes, 13 de octubre de 2020 15:54
Para: karthik947/BinanceTriangularArbitrage_v2 <BinanceTriangularArbitrage_v2@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [karthik947/BinanceTriangularArbitrage_v2] Commercial version (#5)

 

Hi bro, how are you?

I've contacted you via your Email according to make this scanning code as a bot that takes actions and get those profits,

We can have a deal about it if you interested,

This is my Email:
a.himite@gmail.com <mailto:a.himite@gmail.com> 

Best Regards,

**Comment by ref-dat** [comment]
I see, ok,

So, do you have other bots we can a deal about maybe?

**Comment by PlinMartinez** [comment]
Dear Friend,

 

Other bots are still in development and I need some months for finish

 

Now, I have a problem personal and I can´t work until 1-2 months

 

 

So, until end of year,beggining next one I don´t have anymore

 

 

 

Best Regards & Saludos,

Manuel Paz

 

De: ref-dat <notifications@github.com> 
Enviado el: martes, 13 de octubre de 2020 16:55
Para: karthik947/BinanceTriangularArbitrage_v2 <BinanceTriangularArbitrage_v2@noreply.github.com>
CC: Plin Martinez <manuelpaz@infopyme.com>; Comment <comment@noreply.github.com>
Asunto: Re: [karthik947/BinanceTriangularArbitrage_v2] Commercial version (#5)

 

I see, ok,

So, do you have other bots we can a deal about maybe?

**Comment by ref-dat** [comment]
I see, ok, thanks for your time bro ;-)
